# Generated by Django 2.2.2 on 2019-06-18 16:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='O valor minimo deve ser 0')])),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='O valor minimo deve ser 0')])),
                ('status', models.CharField(choices=[('PAID_OUT', 1), ('PENDING', 0), ('SCHEDULED', 2)], default=('PENDING', 0), max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BillingCicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='O valor minimo deve ser 1'), django.core.validators.MinValueValidator(12, message='O valor maximo deve ser 12')])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1970, message='O valor minimo deve ser 1970'), django.core.validators.MinValueValidator(2200, message='O valor maximo deve ser 2200')])),
                ('credits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingCicle.Credit')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingCicle.Debit')),
            ],
        ),
    ]
