# Generated by Django 2.2.2 on 2019-06-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingCicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingcicle',
            old_name='debit',
            new_name='debits',
        ),
    ]
