# Generated by Django 2.2.2 on 2019-06-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillingCicle', '0005_auto_20190618_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcicle',
            name='credits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingCicle.Credit'),
        ),
        migrations.AlterField(
            model_name='billingcicle',
            name='debits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingCicle.Debit'),
        ),
    ]
