# Generated by Django 2.2.2 on 2019-06-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingCicle', '0006_auto_20190618_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingcicle',
            name='credits',
        ),
        migrations.AddField(
            model_name='billingcicle',
            name='credits',
            field=models.ManyToManyField(to='BillingCicle.Credit'),
        ),
        migrations.RemoveField(
            model_name='billingcicle',
            name='debits',
        ),
        migrations.AddField(
            model_name='billingcicle',
            name='debits',
            field=models.ManyToManyField(to='BillingCicle.Debit'),
        ),
    ]
