# Generated by Django 2.2.3 on 2019-07-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingCicle', '0007_auto_20190618_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='status',
            field=models.CharField(choices=[(1, 'PAID_OUT'), (0, 'PENDING'), (2, 'SCHEDULED')], default=(0, 'PENDING'), max_length=10),
        ),
    ]
